### ISSUE TITLE
Crash on Group.update

### ISSUE THREAD

**Issue by Nikita22007** [Nikita22007/pixel-dungeon-multiplayer-server#1]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.contains(java.lang.Object)' on a null object reference
    at com.watabou.noosa.Group.update(Group.java:65)
    at com.watabou.noosa.Scene.update(Scene.java:65)
    at com.watabou.pixeldungeon.scenes.GameScene.update(GameScene.java:266)
    at com.watabou.noosa.Game.update(Game.java:341)
    at com.watabou.noosa.Game.step(Game.java:303)
    at com.watabou.noosa.Game.server_step(Game.java:210)
    at com.watabou.pixeldungeon.network.Server$1.run(Server.java:58)
 END OF LOG *
Anroid 12 Start game in Cras

**Comment by Nikita22007** [comment]
fixed
